### ISSUE TITLE
onScrollsToTop callback is never called

### ISSUE THREAD

**Issue by vincepunkrock** [optimist-dev/scrolls_to_top#4]
No matter where I put the ScrollsToTop widget in my app, the onScrollsToTop is never called.

I tried 
- at the very top level (in main.dart, around the home widget)
- around the Scaffold of the widget which is containing the bottomNavigationBar
- around the Scaffold of any other pages widget
- around the ListView widget

I do have multiple navigators. One per tab in the bottom navigation bar. 

How can I use the ScrollsToTop widget in this case?

**Comment by otopba** [comment]
Hey!
Please check Warning https://github.com/optimist-dev/scrolls_to_top#warning
"If you use several Navigators, the tap events will come only to the widgets inside the main Navigator"

Can you provide a minimal example and I'll try to figure out how to fix it?

**Comment by otopba** [comment]
Due to the fact that there has been no response for a long time, I am closing this thread. If the problem recurs, please write to this thread again

**Comment by simplenotezy** [comment]
@otopba  Just FYI I also tried playing around with the repository for half an hour but wasn't able to get it working. Since it isn't a high priority feature, we postponed it for now. Would love to deliver a reproducible example, but currently lack the time to do so.

Not entirely sure what you mean by "if you use several navigators". We use auto_route for our project, and have a bottom navigation bar that replaces different routes.

According to documentation you should wrap the content in Scaffold, but that wasn't sufficient apparently.
